### ISSUE TITLE
"Off" option for GitHub position is not showing up in Grav Admin

### ISSUE THREAD

**Issue by rbukovansky** [getgrav/grav-theme-learn2#47]
It seems to me that "off" option for GitHub position is not processed correctly by Grav Admin and not shown in combobox. Can you do anything about it or should I log issue with Grav Admin directly? Thanks.

![screen shot 2017-02-09 at 15 22 14](https://cloud.githubusercontent.com/assets/1004491/22787146/96b24320-eedb-11e6-8f8b-d0150eb70923.png)

**Comment by flaviocopes** [comment]
I see it fine in the latest release. Tested the RTFM skeleton
🤔  

![screen shot 2017-02-09 at 18 36 00](https://cloud.githubusercontent.com/assets/11783388/22795403/e4104340-eef6-11e6-942e-a629ff467abb.png)

**Comment by rbukovansky** [comment]
Not for me... Took actual plain RTFM-skeleton from [getgrav.org](https://getgrav.org/download/skeletons/rtfm-site/1.0.2), no changes, except `bin/gpm install admin` and that option is not there... :thinking:

Fedora 25 Server
Apache 2.4.25
PHP 7.0.15

**Comment by flaviocopes** [comment]
The `user/themes/learn2/blueprints.yaml` file contains the "Off" option?

**Comment by rbukovansky** [comment]
Yup... 
![screen shot 2017-02-10 at 11 04 53](https://cloud.githubusercontent.com/assets/1004491/22822724/d76ce654-ef80-11e6-8765-8d228aa1ee62.png)

**Comment by flaviocopes** [comment]
If you change "off" to something else, does it work? Anyone else can replicate the issue?

**Comment by rbukovansky** [comment]
Yes, those two other options work just fine.

**Comment by flaviocopes** [comment]
I mean, if you change `off: Off` to `offtest: Offtest` for example, does it work? To check if it's the specific string causing the problem

**Comment by rbukovansky** [comment]
Changing it to `offtest: Offtest` works. Reverting back to `off: Off` doesn't.

**Comment by ZapTechAdmin** [comment]
I know I am a bit late, but @rbukovansky you can edit the yaml file in user/config/themes/learn2.yaml (make it if it doesn't exist) and add the following text:
```
top_level_version: false
home_url:
github:
    enabled: false
    position: off
    tree: https://github.com/getgrav/grav-skeleton-rtfm-site/blob/develop/
    commits: https://github.com/getgrav/grav-skeleton-rtfm-site/commits/develop/
```
Ensure that the text after position is off. There you go!
