### ISSUE TITLE
Brazilian translation

### ISSUE THREAD

**Issue by enzimage** [getgrav/grav-theme-learn2#60]
Please add the Brazilian Portuguese translation to the languages.yaml file:
```
pt-br:
    THEME_LEARN2_GITHUB_EDIT_THIS_PAGE: editar esta página
    THEME_LEARN2_GITHUB_NOTE: Encontrou erros? Será que você consegue melhorar esta documentação?
    THEME_LEARN2_CLEAR_HISTORY: Limpar Histórico
    THEME_LEARN2_BUILT_WITH_GRAV: Criado usando <a href="http://getgrav.org">Grav</a> - O CMS moderno de arquivos planos
    THEME_LEARN2_SEARCH_DOCUMENTATION: Procurar documentação
```
